name: Build & Deploy React application

on:
    push:
        branches:
            - main

jobs:
    build-deploy:
        name: Build & Deploy React application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '14'

            - name: Install dependencies
              run: npm install --force

            - name: Build the application
              run: npm run build

            - name: Build FE Docker Image
              uses: docker/build-push-action@v2
              with:
                  context: .
                  dockerfile: Dockerfile
                  push: false
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-exe-react

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Push FE to Docker Hub
              uses: docker/build-push-action@v2
              with:
                  context: .
                  dockerfile: Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-exe-react

            # Uncomment the following block to deploy to AWS
            # - name: Deploy FE to AWS Server
            #   uses: appleboy/ssh-action@master
            #   with:
            #     host: ${{ secrets.FE_AWS_SERVER_HOST }}
            #     username: ${{ secrets.AWS_SERVER_USERNAME }}
            #     key: ${{ secrets.FE_AWS_SERVER_SSH_KEY }}
            #     port: ${{ secrets.AWS_SERVER_SSH_PORT }}
            #     script: |
            #       sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-exe-react:latest
            #       sudo docker stop frontend-exe-react || true
            #       sudo docker rm frontend-exe-react || true
            #       sudo docker run -d --name frontend-exe-react -p 80:3000 ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-exe-react:latest
